# Requirements:
#     - 256 color support
#     - Powerline font installed
#     - Unicode support

__set_theme() {
    # Load the 'colorful' theme...
    source "$(__get_script_dir)/themes/colorful.theme"
    __set_theme

    # ...and change the colors
    BASH_POWERPROMPT_THEME="hybrid"
    BASH_POWERPROMPT_FG_COLORS=(15 15 15 15 15 15 15 15)
    BASH_POWERPROMPT_BG_COLORS=(65 60 60 60 167 110 110 221)
}
