# Requirements:
#     - 256 color support
#     - Powerline font installed
#     - Unicode support

__bpp_set_theme() {
    __load_theme "colorful"

    BASH_POWERPROMPT_THEME="hybrid"

    # Override all colors except for the git state
    BASH_POWERPROMPT_FG_COLORS[0]=15
    BASH_POWERPROMPT_FG_COLORS[1]=15
    BASH_POWERPROMPT_FG_COLORS[2]=15
    BASH_POWERPROMPT_FG_COLORS[3]=15
    BASH_POWERPROMPT_FG_COLORS[4]=15
    BASH_POWERPROMPT_FG_COLORS[5]=15
    BASH_POWERPROMPT_FG_COLORS[7]=15
    BASH_POWERPROMPT_BG_COLORS=(65 60 60 60 167 110 110 221)
}
