#!/usr/bin/env bash
#
# Requirements:
#     - True-color support
#     - Powerline font installed
#     - Unicode support
#     - git

__bpp_set_theme() {
    BASH_POWERPROMPT_THEME='katana'
    BASH_POWERPROMPT_COLOR_FORMAT=$BASH_POWERPROMPT_COLOR_FORMAT_16
    BASH_POWERPROMPT_LEFT_PADDING=()
    BASH_POWERPROMPT_RIGHT_PADDING=()
    BASH_POWERPROMPT_SEPARATORS=('' ')-(' ')-(' ')-(' ')-(' '')

    # Predefined colors
    local blue='34'
    local green='32'
    local white='37'
    local bright="${BPP_THEME_KATANA_BRIGHT:=0}"

    if [ "$bright" -eq 1 ]; then
        blue='1;34'
        green='1;32'
        white='1;37'
    fi

    BASH_POWERPROMPT_FG_COLORS=($white $blue $blue $blue $green $green $white '' $white)
    BASH_POWERPROMPT_BG_COLORS=('' '' '' '' '' '' '' '' '')

    local file_count="$(ls -1 | wc -l | sed 's: ::g')"
    local file_sizes="$(du -sh . | sed -E 's/\s*([0-9]+(\.[0-9]+)?[a-zA-Z]).*/\1/')"

    BASH_POWERPROMPT_SECTIONS=(
        "┏ ("
        "\u@\h"
        "$BASH_POWERPROMPT_EXIT_STATUS"
        "\t \d"
        "\w"
        "$file_count files, ${file_sizes}"
        ")"
        "\n"
        "┗ ➞ "
    )
}
