__bpp_set_theme() {
    BASH_POWERPROMPT_THEME="random"

    local random_file=""
    local random_theme="random"

    # Loop until we pick any theme but the 'random' theme itself
    while [ "$random_theme" = "random" ]; do
        # Pick a random file from the themes directory and set it as the current theme
        local script_dir="$(__get_script_dir)"
        local files=($script_dir/themes/*.theme)
        random_file="${files[RANDOM % ${#files[@]}]}"

        # Strip the path and extension from the file
        random_theme="${random_file##*/}"
        random_theme="${random_theme%.theme}"
    done

    printf "Selected random theme '%s'\n" "$random_theme"

    source "$random_file"
    __bpp_set_theme
}
