#!/usr/bin/env bash

# Requirements:
#     - 256 color support

__bpp_set_theme() {
    BASH_POWERPROMPT_THEME='simplistic'
    BASH_POWERPROMPT_COMMAND_SYMBOL=$(printf "%b" "\xe2\x86\x92")
    BASH_POWERPROMPT_LEFT_PADDING=('' '' '' '' '')
    BASH_POWERPROMPT_RIGHT_PADDING=('' '' '' '' '')
    BASH_POWERPROMPT_BG_COLORS=('' '' '' '')
    BASH_POWERPROMPT_SEPARATOR_FG_COLORS=('' '' '')
    BASH_POWERPROMPT_SEPARATOR_BG_COLORS=('' '' '')
    BASH_POWERPROMPT_FG_COLORS=(113 15 74 15)
    BASH_POWERPROMPT_SECTIONS=("\u" "at" "\W" "$BASH_POWERPROMPT_COMMAND_SYMBOL")
    BASH_POWERPROMPT_SEPARATORS=(' ' ' ' ' ')

    # Load git utility functions
    __load_utility "git"

    local git_branch="$(__git_branch)"

    if [ -n "$git_branch" ]; then
        BASH_POWERPROMPT_BG_COLORS=("${BASH_POWERPROMPT_BG_COLORS[@]}" '')
        BASH_POWERPROMPT_SEPARATOR_FG_COLORS=(${BASH_POWERPROMPT_SEPARATOR_FG_COLORS[@]} '' '')
        BASH_POWERPROMPT_SEPARATOR_BG_COLORS=(${BASH_POWERPROMPT_SEPARATOR_BG_COLORS[@]} '' '')
        BASH_POWERPROMPT_FG_COLORS=(113 15 74 15 99 15)
        BASH_POWERPROMPT_SECTIONS=("${BASH_POWERPROMPT_SECTIONS[@]:0:3}" "on" "$git_branch" "$BASH_POWERPROMPT_COMMAND_SYMBOL")
        BASH_POWERPROMPT_SEPARATORS=("${BASH_POWERPROMPT_SEPARATORS[@]}" ' ' ' ')
    fi
}
