# Requirements:
#     - 256 color support
#     - Powerline font installed
#     - Unicode support

__bpp_set_theme() {
    # Load the 'colorful' theme...
    __load_theme "colorful"

    # After loading the 'colorful' theme we need to check if we are on a git branch
    local on_git_branch=0
    [ -z "${BASH_POWERPROMPT_SEPARATORS[5]}" ] && on_git_branch=1

    # ...and change the colors
    BASH_POWERPROMPT_THEME="solarized_light"
    BASH_POWERPROMPT_FG_COLORS=(37 33 33 33 136 166 166 64)
    BASH_POWERPROMPT_BG_COLORS=(230 230 230 230 230 230 230 230)
    BASH_POWERPROMPT_SEPARATOR_FG_COLORS=(246 246 246 246 246 246 246 230)
    BASH_POWERPROMPT_SEPARATOR_BG_COLORS=(230 230 230 230 230 230 230 230)
    BASH_POWERPROMPT_SEPARATORS=(
        $BASH_POWERPROMPT_THIN_ARROW_SYMBOL
        ""
        ""
        $BASH_POWERPROMPT_THIN_ARROW_SYMBOL
        $BASH_POWERPROMPT_THIN_ARROW_SYMBOL
        $BASH_POWERPROMPT_THIN_ARROW_SYMBOL
        $BASH_POWERPROMPT_THIN_ARROW_SYMBOL
        $BASH_POWERPROMPT_SOLID_ARROW_SYMBOL
    )

    # Remove the separator between the git branch name and the git state
    # symbol if we are on a git branch
    [ $on_git_branch -eq 1 ] && BASH_POWERPROMPT_SEPARATORS[5]=""
}
